---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: f2839hfd
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: h892d3hg
      version: '>15.0.0'
  interval: 1m0s
  releaseName: podinfo

