---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: d3h892dhs3
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: d32h98hsdj

